name: Arduino CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        sketchDirectory: ./
        board: "arduino:avr:uno"
